export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_PRODUCT_TO_CART = 'DELETE_PRODUCT_TO_CART';
export const ON_CHANGE_MESSAGE="ON_CHANGE_MESSAGE";
export const UPDATE_PRODUCT="UPDATE_PRODUCT";
